# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/moto/spyder/extract-files.sh

# All the blobs necessary for spyder

#bootclasspath jars
#PRODUCT_COPY_FILES += \
#vendor/moto/spyder/proprietary/com.motorola.android.frameworks.jar:/system/framework/com.motorola.android.frameworks.jar \
#vendor/moto/spyder/proprietary/com.motorola.android.widget.jar:/system/framework/com.motorola.android.widget.jar \
#vendor/moto/spyder/proprietary/com.motorola.device.jar:/system/framework/com.motorola.device.jar \
#vendor/moto/spyder/proprietary/com.orange.authentication.simcard.jar:/system/framework/com.orange.authentication.simcard.jar \

# system/bin
PRODUCT_COPY_FILES += \
vendor/moto/spyder/proprietary/Hostapd:/system/bin/Hostapd \
vendor/moto/spyder/proprietary/akmd8975:/system/bin/akmd8975 \
vendor/moto/spyder/proprietary/ap_gain.bin:/system/bin/ap_gain.bin \
vendor/moto/spyder/proprietary/ap_gain_mmul.bin:/system/bin/ap_gain_mmul.bin \
vendor/moto/spyder/proprietary/batch:/system/bin/batch \
vendor/moto/spyder/proprietary/btcmd:/system/bin/btcmd \
vendor/moto/spyder/proprietary/bthelp:/system/bin/bthelp \
vendor/moto/spyder/proprietary/bttest_mot:/system/bin/bttest_mot \
vendor/moto/spyder/proprietary/charge_only_mode:/system/bin/charge_only_mode \
vendor/moto/spyder/proprietary/chat-ril:/system/bin/chat-ril \
vendor/moto/spyder/proprietary/dbvc_atvc_property_set:/system/bin/dbvc_atvc_property_set \
vendor/moto/spyder/proprietary/dmt:/system/bin/dmt \
vendor/moto/spyder/proprietary/dumpe2fs:/system/bin/dumpe2fs \
vendor/moto/spyder/proprietary/dund:/system/bin/dund \
vendor/moto/spyder/proprietary/ecckeyd:/system/bin/ecckeyd \
vendor/moto/spyder/proprietary/enable_mdm_usb_suspend.sh:/system/bin/enable_mdm_usb_suspend.sh \
vendor/moto/spyder/proprietary/enc_mgt_tool:/system/bin/enc_mgt_tool \
vendor/moto/spyder/proprietary/fbread:/system/bin/fbread \
vendor/moto/spyder/proprietary/ftmipcd:/system/bin/ftmipcd \
vendor/moto/spyder/proprietary/gkilogd:/system/bin/gkilogd \
vendor/moto/spyder/proprietary/hdcp-mknod:/system/bin/hdcp-mknod \
vendor/moto/spyder/proprietary/modemlog:/system/bin/modemlog \
vendor/moto/spyder/proprietary/mot_boot_mode:/system/bin/mot_boot_mode \
vendor/moto/spyder/proprietary/msp430:/system/bin/msp430 \
vendor/moto/spyder/proprietary/napics.sh:/system/bin/napics.sh \
vendor/moto/spyder/proprietary/secclkd:/system/bin/secclkd \
vendor/moto/spyder/proprietary/startup_smc.sh:/system/bin/startup_smc.sh \
vendor/moto/spyder/proprietary/tcmd:/system/bin/tcmd \
vendor/moto/spyder/proprietary/tcmdhelp:/system/bin/tcmdhelp \
vendor/moto/spyder/proprietary/testpppd:/system/bin/testpppd \
vendor/moto/spyder/proprietary/tiap_loader:/system/bin/tiap_loader \
vendor/moto/spyder/proprietary/tty2ttyd:/system/bin/tty2ttyd \
vendor/moto/spyder/proprietary/usbd:/system/bin/usbd \
vendor/moto/spyder/proprietary/whisperd:/system/bin/whisperd \
vendor/moto/spyder/proprietary/vpnclientpm:/system/bin/vpnclientpm \
vendor/moto/spyder/proprietary/bugtogo.sh:/system/bin/bugtogo.sh \
vendor/moto/spyder/proprietary/motobox:/system/bin/motobox \
#vendor/moto/spyder/proprietary/battd:/system/bin/battd \
#vendor/moto/spyder/proprietary/dlnasrv:/system/bin/dlnasrv \
#vendor/moto/spyder/proprietary/ip:/system/bin/ip \
#vendor/moto/spyder/proprietary/loadpreinstalls.sh:/system/bin/loadpreinstalls.sh \
#vendor/moto/spyder/proprietary/memtest_mode:/system/bin/memtest_mode \
#vendor/moto/spyder/proprietary/motobox:/system/bin/motobox \
#vendor/moto/spyder/proprietary/smc_pa_ctrl:/system/bin/smc_pa_ctrl \
#vendor/moto/spyder/proprietary/tf_daemon:/system/bin/tf_daemon \
#vendor/moto/spyder/proprietary/tstmetainfo:/system/bin/tstmetainfo \
#vendor/moto/spyder/proprietary/vold:/system/bin/vold \
#vendor/moto/spyder/proprietary/tund:/system/bin/tund \


# system/etc
PRODUCT_COPY_FILES += \
vendor/moto/spyder/proprietary/01_Vendor_ti_omx.cfg:/system/etc/01_Vendor_ti_omx.cfg \
vendor/moto/spyder/proprietary/backup_targets.csv:/system/etc/backup_targets.csv \
vendor/moto/spyder/proprietary/btpan.conf:/system/etc/btpan.conf \
vendor/moto/spyder/proprietary/ecryptfs.exc:/system/etc/ecryptfs.exc \
vendor/moto/spyder/proprietary/ecryptfs.tab:/system/etc/ecryptfs.tab \
vendor/moto/spyder/proprietary/encrypt.tab:/system/etc/encrypt.tab \
vendor/moto/spyder/proprietary/event-log-tags:/system/etc/event-log-tags \
vendor/moto/spyder/proprietary/excluded-input-devices.xml:/system/etc/excluded-input-devices.xml \
vendor/moto/spyder/proprietary/hdmiSolDefLg.gif:/system/etc/hdmiSolDefLg.gif \
vendor/moto/spyder/proprietary/hdmiSolDefSm.gif:/system/etc/hdmiSolDefSm.gif \
vendor/moto/spyder/proprietary/opl.dat.enc:/system/etc/opl.dat.enc \
vendor/moto/spyder/proprietary/priority_notifications_config.xml:/system/etc/priority_notifications_config.xml \
vendor/moto/spyder/proprietary/pvplayer.cfg:/system/etc/pvplayer.cfg \
vendor/moto/spyder/proprietary/qewl.jar:/system/etc/qewl.jar \
vendor/moto/spyder/proprietary/supportedlocales.conf:/system/etc/supportedlocales.conf \
vendor/moto/spyder/proprietary/smc_android_cfg.ini:/system/etc/smc_android_cfg.ini \
vendor/moto/spyder/proprietary/smc_pa.ift:/system/etc/smc_pa.ift \
vendor/moto/spyder/proprietary/smc_pa_pk_4_8Mb_ipa.bin:/system/etc/smc_pa_pk_4_8Mb_ipa.bin \
vendor/moto/spyder/proprietary/smc_pa_pk_4_ipa.bin:/system/etc/smc_pa_pk_4_ipa.bin \
vendor/moto/spyder/proprietary/mspfirmware.bin:/system/etc/mspfirmware/mspfirmware.bin \
vendor/moto/spyder/proprietary/version.txt:/system/etc/mspfirmware/version.txt \

#vendor/moto/spyder/proprietary/TIInit_10.6.15.bts:/system/etc/firmware/TIInit_10.6.15.bts \

# system/etc/(others)
PRODUCT_COPY_FILES += \
vendor/moto/spyder/proprietary/ap_bt_data.bin:/system/etc/firmware/ap_bt_data.bin \
vendor/moto/spyder/proprietary/fm_rx_init_1283.2.bts:/system/etc/firmware/fm_rx_init_1283.2.bts \
vendor/moto/spyder/proprietary/fmc_init_1283.2.bts:/system/etc/firmware/fmc_init_1283.2.bts \
vendor/moto/spyder/proprietary/vsuite_config.xml:/system/etc/nuance/vsuite_config.xml \
vendor/moto/spyder/proprietary/R8_MVEN002_LD2_ND0_IR0_SH0_FL1_SVEN002_DCCID1039.cfg:/system/etc/omapcam/R8_MVEN002_LD2_ND0_IR0_SH0_FL1_SVEN002_DCCID1039.cfg \
vendor/moto/spyder/proprietary/R8_MVEN002_LD2_ND0_IR0_SH0_FL1_SVEN002_DCCID1039_CAL.cfg:/system/etc/omapcam/R8_MVEN002_LD2_ND0_IR0_SH0_FL1_SVEN002_DCCID1039_CAL.cfg \
vendor/moto/spyder/proprietary/R8_MVEN002_LD2_ND0_IR0_SH0_FL1_SVEN002_DCCID1039_EE.cfg:/system/etc/omapcam/R8_MVEN002_LD2_ND0_IR0_SH0_FL1_SVEN002_DCCID1039_EE.cfg \
vendor/moto/spyder/proprietary/SEN2.cfg:/system/etc/omapcam/SEN2.cfg \
vendor/moto/spyder/proprietary/SEN2_EE.cfg:/system/etc/omapcam/SEN2_EE.cfg \
vendor/moto/spyder/proprietary/cid1039_cid1039_capabilities.bin:/system/etc/omapcam/module1.bak/cid1039_cid1039_capabilities.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_alg_3a_ae_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_ae_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_alg_3a_ae_mms2_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_ae_mms2_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_alg_3a_af_affw_dcc_tuning.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_affw_dcc_tuning.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_alg_3a_af_caf_dcc_tuning.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_caf_dcc_tuning.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_alg_3a_af_hllc_dcc_tuning.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_hllc_dcc_tuning.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_alg_3a_af_saf_dcc_tuning.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_saf_dcc_tuning.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_alg_adjust_rgb2rgb_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_alg_adjust_rgb2rgb_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_awb_alg_ti3_tuning.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_awb_alg_ti3_tuning.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ducati_eff_tun.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ducati_eff_tun.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ducati_lsc_2d.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ducati_lsc_2d.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_golden_module_calibration.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_golden_module_calibration.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_h3a_aewb_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_h3a_aewb_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ipipe_3d_lut_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_3d_lut_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ipipe_car_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_car_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ipipe_cfai_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_cfai_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ipipe_cgs_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_cgs_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ipipe_dpc_lut_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_dpc_lut_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ipipe_dpc_otf.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_dpc_otf.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ipipe_gbce_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_gbce_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ipipe_gic_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_gic_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ipipe_lsc_poly_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_lsc_poly_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ipipe_nf1_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_nf1_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ipipe_nf2_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_nf2_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ipipe_rgb2rgb_1_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rgb2rgb_1_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ipipe_rgb2rgb_2_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rgb2rgb_2_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ipipe_rgb2yuv_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rgb2yuv_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ipipe_rsz_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rsz_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ipipe_yuv444_to_yuv422_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_yuv444_to_yuv422_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_isif_csc_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_isif_csc_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_iss_glbce3_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_iss_glbce3_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_iss_lbce_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_iss_lbce_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_iss_scene_modes_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_iss_scene_modes_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ldc_cac_cfg_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ldc_cac_cfg_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ldc_cfg_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ldc_cfg_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_vnf_cfg_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_vnf_cfg_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_lsc_interp.bin:/system/etc/omapcam/module1_cal/cid1039_ov8820_lsc_interp.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_isif_clamp_dcc.bin:/system/etc/omapcam/module1_cal/cid1039_ov8820_isif_clamp_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ipipe_ee_dcc.bin:/system/etc/omapcam/module1_cal/cid1039_ov8820_ipipe_ee_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_gbce_sw1_dcc.bin:/system/etc/omapcam/module1_cal/cid1039_ov8820_gbce_sw1_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ducati_nsf_ldc.bin:/system/etc/omapcam/module1_cal/cid1039_ov8820_ducati_nsf_ldc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ducati_gamma.bin:/system/etc/omapcam/module1_cal/cid1039_ov8820_ducati_gamma.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_alg_3a_ae_mms2_dcc.bin:/system/etc/omapcam/module1_cal/cid1039_ov8820_alg_3a_ae_mms2_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ducati_gamma.bin:/system/etc/omapcam/module1_ee/cid1039_ov8820_ducati_gamma.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ducati_nsf_ldc.bin:/system/etc/omapcam/module1_ee/cid1039_ov8820_ducati_nsf_ldc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ipipe_ee_dcc.bin:/system/etc/omapcam/module1_ee/cid1039_ov8820_ipipe_ee_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_isif_clamp_dcc.bin:/system/etc/omapcam/module1_ee/cid1039_ov8820_isif_clamp_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_lsc_interp.bin:/system/etc/omapcam/module1_ee/cid1039_ov8820_lsc_interp.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ducati_gamma.bin:/system/etc/omapcam/module1_rel.bak/cid1039_ov8820_ducati_gamma.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ducati_gamma.bin:/system/etc/omapcam/module1_rel.bak/cid1039_ov8820_ducati_gamma.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ducati_gamma.bin:/system/etc/omapcam/module1_rel.bak/cid1039_ov8820_ducati_gamma.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ipipe_ee_dcc.bin:/system/etc/omapcam/module1_rel.bak/cid1039_ov8820_ipipe_ee_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_ipipe_ee_dcc.bin:/system/etc/omapcam/module1_rel.bak/cid1039_ov8820_ipipe_ee_dcc.bin \
vendor/moto/spyder/proprietary/cid1039_ov8820_lsc_interp.bin:/system/etc/omapcam/module1_rel.bak/cid1039_ov8820_lsc_interp.bin \
vendor/moto/spyder/proprietary/cid1042_mt9m114_sensor_config_dcc.bin:/system/etc/omapcam/module2/cid1042_mt9m114_sensor_config_dcc.bin \
vendor/moto/spyder/proprietary/cid1042_mt9m114_sensor_config_dcc.bin:/system/etc/omapcam/module2_ee/cid1042_mt9m114_sensor_config_dcc.bin \
vendor/moto/spyder/proprietary/pppd-ril.options:/system/etc/ppp/peers/pppd-ril.options \
vendor/moto/spyder/proprietary/en_US.aff:/system/etc/spellchecker/en_US.aff \
vendor/moto/spyder/proprietary/en_US.dic:/system/etc/spellchecker/en_US.dic \
vendor/moto/spyder/proprietary/es_ES.aff:/system/etc/spellchecker/es_ES.aff \
vendor/moto/spyder/proprietary/es_ES.dic:/system/etc/spellchecker/es_ES.dic \
vendor/moto/spyder/proprietary/google_generic_update.txt:/system/etc/updatecmds/google_generic_update.txt \
vendor/moto/spyder/proprietary/mve.ini:/system/etc/VideoEditorLite/mve.ini \
vendor/moto/spyder/proprietary/MeaningFulLocation.vsensor:/system/etc/vsensor.d/MeaningFulLocation.vsensor \
vendor/moto/spyder/proprietary/fw_wlan1281.bin:/system/etc/wifi/fw_wlan1281.bin \
vendor/moto/spyder/proprietary/fw_wlan1281_AP.bin:/system/etc/wifi/fw_wlan1281_AP.bin \
vendor/moto/spyder/proprietary/hostapd.conf.templet:/system/etc/wifi/hostapd.conf.templet \
vendor/moto/spyder/proprietary/00main:system/usr/share/alsa/init/00main \
vendor/moto/spyder/proprietary/default:system/usr/share/alsa/init/default \
vendor/moto/spyder/proprietary/hda:system/usr/share/alsa/init/hda \
vendor/moto/spyder/proprietary/info:system/usr/share/alsa/init/info \
vendor/moto/spyder/proprietary/test:system/usr/share/alsa/init/test \
vendor/moto/spyder/proprietary/alsa.conf:system/usr/share/alsa/alsa.conf \
vendor/moto/spyder/proprietary/aliases.conf:system/usr/share/alsa/cards/aliases.conf \
vendor/moto/spyder/proprietary/center_lfe.conf:system/usr/share/alsa/pcm/center_lfe.conf \
vendor/moto/spyder/proprietary/default.conf:system/usr/share/alsa/pcm/default.conf \
vendor/moto/spyder/proprietary/dmix.conf:system/usr/share/alsa/pcm/dmix.conf \
vendor/moto/spyder/proprietary/dpl.conf:system/usr/share/alsa/pcm/dpl.conf \
vendor/moto/spyder/proprietary/dsnoop.conf:system/usr/share/alsa/pcm/dsnoop.conf \
vendor/moto/spyder/proprietary/front.conf:system/usr/share/alsa/pcm/front.conf \
vendor/moto/spyder/proprietary/iec958.conf:system/usr/share/alsa/pcm/iec958.conf \
vendor/moto/spyder/proprietary/modem.conf:system/usr/share/alsa/pcm/modem.conf \
vendor/moto/spyder/proprietary/rear.conf:system/usr/share/alsa/pcm/rear.conf \
vendor/moto/spyder/proprietary/side.conf:system/usr/share/alsa/pcm/side.conf \
vendor/moto/spyder/proprietary/surround40.conf:system/usr/share/alsa/pcm/surround40.conf \
vendor/moto/spyder/proprietary/surround41.conf:system/usr/share/alsa/pcm/surround41.conf \
vendor/moto/spyder/proprietary/surround50.conf:system/usr/share/alsa/pcm/surround50.conf \
vendor/moto/spyder/proprietary/surround51.conf:system/usr/share/alsa/pcm/surround51.conf \
vendor/moto/spyder/proprietary/surround71.conf:system/usr/share/alsa/pcm/surround71.conf

# system/lib
PRODUCT_COPY_FILES += \
vendor/moto/spyder/proprietary/libadkutils.so:/system/lib/libadkutils.so \
vendor/moto/spyder/proprietary/libamcm.so:/system/lib/libamcm.so \
vendor/moto/spyder/proprietary/libbattd.so:/system/lib/libbattd.so \
vendor/moto/spyder/proprietary/libbcbmsg.so:/system/lib/libbcbmsg.so \
vendor/moto/spyder/proprietary/libbt-aptx.so:/system/lib/libbt-aptx.so \
vendor/moto/spyder/proprietary/libbt-mp3.so:/system/lib/libbt-mp3.so \
vendor/moto/spyder/proprietary/libbt-mpeg12pl.so:/system/lib/libbt-mpeg12pl.so \
vendor/moto/spyder/proprietary/libcaps.so:/system/lib/libcaps.so \
vendor/moto/spyder/proprietary/libcapsjava.so:/system/lib/libcapsjava.so \
vendor/moto/spyder/proprietary/libdlnahttpjni.so:/system/lib/libdlnahttpjni.so \
vendor/moto/spyder/proprietary/libdlnajni.so:/system/lib/libdlnajni.so \
vendor/moto/spyder/proprietary/libdlnaprofileparser.so:/system/lib/libdlnaprofileparser.so \
vendor/moto/spyder/proprietary/libdlnasysjni.so:/system/lib/libdlnasysjni.so \
vendor/moto/spyder/proprietary/libdmengine.so:/system/lib/libdmengine.so \
vendor/moto/spyder/proprietary/libdmjavaplugin.so:/system/lib/libdmjavaplugin.so \
vendor/moto/spyder/proprietary/libexempi.so:/system/lib/libexempi.so \
vendor/moto/spyder/proprietary/libextdisp.so:/system/lib/libextdisp.so \
vendor/moto/spyder/proprietary/libfmchr.so:/system/lib/libfmchr.so \
vendor/moto/spyder/proprietary/libfm_stack.so:/system/lib/libfm_stack.so \
vendor/moto/spyder/proprietary/libhdcp.so:/system/lib/libhdcp.so \
vendor/moto/spyder/proprietary/libhdmi.so:/system/lib/libhdmi.so \
vendor/moto/spyder/proprietary/libhostapd_client.so:/system/lib/libhostapd_client.so \
vendor/moto/spyder/proprietary/libimage_jni.so:/system/lib/libimage_jni.so \
vendor/moto/spyder/proprietary/libjanus.so:/system/lib/libjanus.so \
vendor/moto/spyder/proprietary/libjni_nwp.so:/system/lib/libjni_nwp.so \
vendor/moto/spyder/proprietary/libkpilogger.so:/system/lib/libkpilogger.so \
vendor/moto/spyder/proprietary/libmetainfo.so:/system/lib/libmetainfo.so \
vendor/moto/spyder/proprietary/libmirror.so:/system/lib/libmirror.so \
vendor/moto/spyder/proprietary/libmirrorjni.so:/system/lib/libmirrorjni.so \
vendor/moto/spyder/proprietary/libmotodbgutils.so:/system/lib/libmotodbgutils.so \
vendor/moto/spyder/proprietary/libmtp_jni.so:/system/lib/libmtp_jni.so \
vendor/moto/spyder/proprietary/libmtpstack.so:/system/lib/libmtpstack.so \
vendor/moto/spyder/proprietary/libnative_renderer.so:/system/lib/libnative_renderer.so \
vendor/moto/spyder/proprietary/libnativedrm1.so:/system/lib/libnativedrm1.so \
vendor/moto/spyder/proprietary/libnbgm.so:/system/lib/libnbgm.so \
vendor/moto/spyder/proprietary/libmotdrm1.so:/system/lib/libmotdrm1.so \
vendor/moto/spyder/proprietary/libmotdrm1_jni.so:/system/lib/libmotdrm1_jni.so \
vendor/moto/spyder/proprietary/libmot_atcmd.so:/system/lib/libmot_atcmd.so \
vendor/moto/spyder/proprietary/libmot_atcmd_mflex.so:/system/lib/libmot_atcmd_mflex.so \
vendor/moto/spyder/proprietary/libmot_bluetooth_jni.so:/system/lib/libmot_bluetooth_jni.so \
vendor/moto/spyder/proprietary/libmot_bthid_jni.so:/system/lib/libmot_bthid_jni.so \
vendor/moto/spyder/proprietary/libmot_btpan_jni.so:/system/lib/libmot_btpan_jni.so \
vendor/moto/spyder/proprietary/libmot_led.so:/system/lib/libmot_led.so \
vendor/moto/spyder/proprietary/libmoto_mdmctrl.so:/system/lib/libmoto_mdmctrl.so \
vendor/moto/spyder/proprietary/libmoto_netutil.so:/system/lib/libmoto_netutil.so \
vendor/moto/spyder/proprietary/libmoto_ril.so:/system/lib/libmoto_ril.so \
vendor/moto/spyder/proprietary/libnmea.so:/system/lib/libnmea.so \
vendor/moto/spyder/proprietary/libpanorama.so:/system/lib/libpanorama.so \
vendor/moto/spyder/proprietary/libpanorama_jni.so:/system/lib/libpanorama_jni.so \
vendor/moto/spyder/proprietary/libPhotoEditor.so:/system/lib/libPhotoEditor.so \
vendor/moto/spyder/proprietary/libphotoflow.so:/system/lib/libphotoflow.so \
vendor/moto/spyder/proprietary/libpkip.so:/system/lib/libpkip.so \
vendor/moto/spyder/proprietary/libpppd_plugin-ril.so:/system/lib/libpppd_plugin-ril.so \
vendor/moto/spyder/proprietary/libprojectM.so:/system/lib/libprojectM.so \
vendor/moto/spyder/proprietary/libprovlib.so:/system/lib/libprovlib.so \
vendor/moto/spyder/proprietary/libquicksec.so:/system/lib/libquicksec.so \
vendor/moto/spyder/proprietary/librds_util.so:/system/lib/librds_util.so \
vendor/moto/spyder/proprietary/libril_rds.so:/system/lib/libril_rds.so \
vendor/moto/spyder/proprietary/libscalado.so:/system/lib/libscalado.so \
vendor/moto/spyder/proprietary/libsmapi.so:/system/lib/libsmapi.so \
vendor/moto/spyder/proprietary/libssmgr.so:/system/lib/libssmgr.so \
vendor/moto/spyder/proprietary/libtexture_mem.so:/system/lib/libtexture_mem.so \
vendor/moto/spyder/proprietary/libtf_crypto_sst.so:/system/lib/libtf_crypto_sst.so \
vendor/moto/spyder/proprietary/libtpa.so:/system/lib/libtpa.so \
vendor/moto/spyder/proprietary/libtpa_core.so:/system/lib/libtpa_core.so \
vendor/moto/spyder/proprietary/libui3d.so:/system/lib/libui3d.so \
vendor/moto/spyder/proprietary/libvideoeditorlite.so:/system/lib/libvideoeditorlite.so \
vendor/moto/spyder/proprietary/libvorbisidec.so:/system/lib/libvorbisidec.so \
vendor/moto/spyder/proprietary/libvpnclient_jni.so:/system/lib/libvpnclient_jni.so \
vendor/moto/spyder/proprietary/libvsuite_mot_vs40_cmb.so:/system/lib/libvsuite_mot_vs40_cmb.so \
vendor/moto/spyder/proprietary/libwbxmlparser.so:/system/lib/libwbxmlparser.so \
vendor/moto/spyder/proprietary/libWifiAPHardware.so:/system/lib/libWifiAPHardware.so \
vendor/moto/spyder/proprietary/libXmp_jni.so:/system/lib/libXmp_jni.so \
vendor/moto/spyder/proprietary/libxmpcore.so:/system/lib/libxmpcore.so \
vendor/moto/spyder/proprietary/moto-ril-multimode.so:/system/lib/moto-ril-multimode.so \
vendor/moto/spyder/proprietary/lib-mot-lte-ril.so:/system/lib/lib-mot-lte-ril.so \
vendor/moto/spyder/proprietary/base64:/system/bin/base64 \
vendor/moto/spyder/proprietary/libb64.so:/system/lib/libb64.so \
vendor/moto/spyder/proprietary/libbabysit.so:/system/lib/libbabysit.so \
vendor/moto/spyder/proprietary/mm-wrigley-qc-dump.sh:/system/bin/mm-wrigley-qc-dump.sh \
vendor/moto/spyder/proprietary/wrigley-diag.sh:/system/bin/wrigley-diag.sh \
vendor/moto/spyder/proprietary/wrigley-dump.sh:/system/bin/wrigley-dump.sh \
vendor/moto/spyder/proprietary/wrigley-fetch-mpr.sh:/system/bin/wrigley-fetch-mpr.sh \
vendor/moto/spyder/proprietary/vril-dump:/system/bin/vril-dump \
vendor/moto/spyder/proprietary/libmoto_nwif_ril.so:/system/lib/libmoto_nwif_ril.so \
vendor/moto/spyder/proprietary/libmoto_qmi_ril.so:/system/lib/libmoto_qmi_ril.so \
vendor/moto/spyder/proprietary/mountosh:/system/bin/mountosh \
vendor/moto/spyder/proprietary/extract-embedded-files:/system/bin/extract-embedded-files \
vendor/moto/spyder/proprietary/libmotdb.so:/system/lib/libmotdb.so \
vendor/moto/spyder/proprietary/libmotintfutil.so:/system/lib/libmotintfutil.so \
vendor/moto/spyder/proprietary/libportaljni.so:/system/lib/libportaljni.so \
vendor/moto/spyder/proprietary/key_code_map.txt:system/etc/motorola/12m/key_code_map.txt \
vendor/moto/spyder/proprietary/suplcerts.bks:system/etc/security/suplcerts.bks \

#vendor/moto/spyder/proprietary/libims_client_jni.so:/system/lib/libims_client_jni.so \
#vendor/moto/spyder/proprietary/libipsec.so:/system/lib/libipsec.so \
# system/lib/ducati
PRODUCT_COPY_FILES += \
vendor/moto/spyder/proprietary/Notify_MPUSYS_reroute_Test_Core0.xem3:/system/lib/ducati/Notify_MPUSYS_reroute_Test_Core0.xem3 \
vendor/moto/spyder/proprietary/base_image_app_m3.xem3:/system/lib/ducati/base_image_app_m3.xem3 \

# system/lib/hw
PRODUCT_COPY_FILES += \
vendor/moto/spyder/proprietary/gps.spyder.so:/system/lib/hw/gps.spyder.so \
vendor/moto/spyder/proprietary/lights.spyder.so:/system/lib/hw/lights.spyder.so \
vendor/moto/spyder/proprietary/sensors.spyder.so:/system/lib/hw/sensors.spyder.so \
vendor/moto/spyder/proprietary/sensorhub.spyder.so:/system/lib/hw/sensorhub.spyder.so \

# system/xbin
PRODUCT_COPY_FILES += \
vendor/moto/spyder/proprietary/drm1_func_test:/system/xbin/drm1_func_test \
vendor/moto/spyder/proprietary/ssmgrd:/system/xbin/ssmgrd \

# All the apks necessary for spyder
PRODUCT_PACKAGES += \
    AppDirectedSmsService \
    MotoImsServer \
    MotoLocationProxy \
    MotoLteTelephony \
    MotoModemUtil \
    ProgramMenu \
    ProgramMenuSystem \
    VZWAPNLib \
    VZWAPNService
