# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by hand

# All the blobs necessary for targa

# system/bin
PRODUCT_COPY_FILES += \
vendor/moto/targa/proprietary/bin/akmd2:/system/bin/akmd2 \
vendor/moto/targa/proprietary/bin/ap_gain.bin:/system/bin/ap_gain.bin \
vendor/moto/targa/proprietary/bin/ap_gain_mmul.bin:/system/bin/ap_gain_mmul.bin \
vendor/moto/targa/proprietary/bin/base64:/system/bin/base64 \
vendor/moto/targa/proprietary/bin/batch:/system/bin/batch \
vendor/moto/targa/proprietary/bin/btcmd:/system/bin/btcmd \
vendor/moto/targa/proprietary/bin/bthelp:/system/bin/bthelp \
vendor/moto/targa/proprietary/bin/bttest_mot:/system/bin/bttest_mot \
vendor/moto/targa/proprietary/bin/bugtogo.sh:/system/bin/bugtogo.sh \
vendor/moto/targa/proprietary/bin/charge_only_mode:/system/bin/charge_only_mode \
vendor/moto/targa/proprietary/bin/chat-ril:/system/bin/chat-ril \
vendor/moto/targa/proprietary/bin/dbvc_atvc_property_set:/system/bin/dbvc_atvc_property_set \
vendor/moto/targa/proprietary/bin/dmt:/system/bin/dmt \
vendor/moto/targa/proprietary/bin/dumpe2fs:/system/bin/dumpe2fs \
vendor/moto/targa/proprietary/bin/dund:/system/bin/dund \
vendor/moto/targa/proprietary/bin/ecckeyd:/system/bin/ecckeyd \
vendor/moto/targa/proprietary/bin/enable_mdm_usb_suspend.sh:/system/bin/enable_mdm_usb_suspend.sh \
vendor/moto/targa/proprietary/bin/enc_mgt_tool:/system/bin/enc_mgt_tool \
vendor/moto/targa/proprietary/bin/encryption_test:/system/bin/encryption_test \
vendor/moto/targa/proprietary/bin/extract-embedded-files:/system/bin/extract-embedded-files \
vendor/moto/targa/proprietary/bin/fbread:/system/bin/fbread \
vendor/moto/targa/proprietary/bin/ftmipcd:/system/bin/ftmipcd \
vendor/moto/targa/proprietary/bin/gkilogd:/system/bin/gkilogd \
vendor/moto/targa/proprietary/bin/hdcp-mknod:/system/bin/hdcp-mknod \
vendor/moto/targa/proprietary/bin/logcatd:/system/bin/logcatd \
vendor/moto/targa/proprietary/bin/logcatd-blan:/system/bin/logcatd-blan \
vendor/moto/targa/proprietary/bin/mdm_panicd:/system/bin/mdm_panicd \
vendor/moto/targa/proprietary/bin/mm-wrigley-qc-dump.sh:/system/bin/mm-wrigley-qc-dump.sh \
vendor/moto/targa/proprietary/bin/modemlog:/system/bin/modemlog \
vendor/moto/targa/proprietary/bin/mot_boot_mode:/system/bin/mot_boot_mode \
vendor/moto/targa/proprietary/bin/motobox:/system/bin/motobox \
vendor/moto/targa/proprietary/bin/mountosh:/system/bin/mountosh \
vendor/moto/targa/proprietary/bin/napics.sh:/system/bin/napics.sh \
vendor/moto/targa/proprietary/bin/pppd-ril:/system/bin/pppd-ril \
vendor/moto/targa/proprietary/bin/pvrsrvinit:/system/bin/pvrsrvinit \
vendor/moto/targa/proprietary/bin/secclkd:/system/bin/secclkd \
vendor/moto/targa/proprietary/bin/start_enc_mgt_tool.sh:/system/bin/start_enc_mgt_tool.sh \
vendor/moto/targa/proprietary/bin/startup_smc.sh:/system/bin/startup_smc.sh \
vendor/moto/targa/proprietary/bin/tcmd:/system/bin/tcmd \
vendor/moto/targa/proprietary/bin/tcmdhelp:/system/bin/tcmdhelp \
vendor/moto/targa/proprietary/bin/testpppd:/system/bin/testpppd \
vendor/moto/targa/proprietary/bin/tty2ttyd:/system/bin/tty2ttyd \
vendor/moto/targa/proprietary/bin/tund:/system/bin/tund \
vendor/moto/targa/proprietary/bin/usbd:/system/bin/usbd \
vendor/moto/targa/proprietary/bin/vril-dump:/system/bin/vril-dump \
vendor/moto/targa/proprietary/bin/vpnclientpm:/system/bin/vpnclientpm \
vendor/moto/targa/proprietary/bin/whisperd:/system/bin/whisperd \
vendor/moto/targa/proprietary/bin/wrigley-diag.sh:/system/bin/wrigley-diag.sh \
vendor/moto/targa/proprietary/bin/wrigley-dump.sh:/system/bin/wrigley-dump.sh \
vendor/moto/targa/proprietary/bin/wrigley-fetch-mpr.sh:/system/bin/wrigley-fetch-mpr.sh \

#vendor/moto/targa/proprietary/bin/battd:/system/bin/battd \
#vendor/moto/targa/proprietary/bin/dlnasrv:/system/bin/dlnasrv \
#vendor/moto/targa/proprietary/bin/ip:/system/bin/ip \
#vendor/moto/targa/proprietary/bin/Hostapd:/system/bin/Hostapd \
#vendor/moto/targa/proprietary/bin/loadpreinstalls.sh:/system/bin/loadpreinstalls.sh \
#vendor/moto/targa/proprietary/bin/memtest_mode:/system/bin/memtest_mode \
#vendor/moto/targa/proprietary/bin/smc_pa_ctrl:/system/bin/smc_pa_ctrl \
#vendor/moto/targa/proprietary/bin/tf_daemon:/system/bin/tf_daemon \
#vendor/moto/targa/proprietary/bin/tiap_loader:/system/bin/tiap_loader \
#vendor/moto/targa/proprietary/bin/tstmetainfo:/system/bin/tstmetainfo \
#vendor/moto/targa/proprietary/bin/vold:/system/bin/vold \


# system/etc
PRODUCT_COPY_FILES += \
vendor/moto/targa/proprietary/etc/01_Vendor_ti_omx.cfg:/system/etc/01_Vendor_ti_omx.cfg \
vendor/moto/targa/proprietary/etc/backup_targets.csv:/system/etc/backup_targets.csv \
vendor/moto/targa/proprietary/etc/btpan.conf:/system/etc/btpan.conf \
vendor/moto/targa/proprietary/etc/dbus.conf:/system/etc/dbus.conf \
vendor/moto/targa/proprietary/etc/ecryptfs.exc:/system/etc/ecryptfs.exc \
vendor/moto/targa/proprietary/etc/ecryptfs.tab:/system/etc/ecryptfs.tab \
vendor/moto/targa/proprietary/etc/event-log-tags:/system/etc/event-log-tags \
vendor/moto/targa/proprietary/etc/excluded-input-devices.xml:/system/etc/excluded-input-devices.xml \
vendor/moto/targa/proprietary/etc/hdmiSolDefLg.gif:/system/etc/hdmiSolDefLg.gif \
vendor/moto/targa/proprietary/etc/hdmiSolDefSm.gif:/system/etc/hdmiSolDefSm.gif \
vendor/moto/targa/proprietary/etc/opl.dat.enc:/system/etc/opl.dat.enc \
vendor/moto/targa/proprietary/etc/priority_notifications_config.xml:/system/etc/priority_notifications_config.xml \
vendor/moto/targa/proprietary/etc/pvplayer.cfg:/system/etc/pvplayer.cfg \
vendor/moto/targa/proprietary/etc/smc_android_cfg.ini:/system/etc/smc_android_cfg.ini \
vendor/moto/targa/proprietary/etc/smc_pa.ift:/system/etc/smc_pa.ift \
vendor/moto/targa/proprietary/etc/smc_pa_pk_4_ipa.bin:/system/etc/smc_pa_pk_4_ipa.bin \
vendor/moto/targa/proprietary/etc/supportedlocales.conf:/system/etc/supportedlocales.conf \

#vendor/moto/targa/proprietary/TIInit_10.6.15.bts:/system/etc/firmware/TIInit_10.6.15.bts \

# system/etc/(others)
PRODUCT_COPY_FILES += \
vendor/moto/targa/proprietary/etc/firmware/ap_bt_data.bin:/system/etc/firmware/ap_bt_data.bin \
vendor/moto/targa/proprietary/etc/firmware/fm_rx_init_1283.2.bts:/system/etc/firmware/fm_rx_init_1283.2.bts \
vendor/moto/targa/proprietary/etc/firmware/fmc_init_1283.2.bts:/system/etc/firmware/fmc_init_1283.2.bts \
vendor/moto/targa/proprietary/etc/nuance/vsuite_config.xml:/system/etc/nuance/vsuite_config.xml \
vendor/moto/targa/proprietary/etc/omapcam/R8_MVEN002_LD2_ND0_IR0_SH0_FL1_SVEN002_DCCID1039.cfg:/system/etc/omapcam/R8_MVEN002_LD2_ND0_IR0_SH0_FL1_SVEN002_DCCID1039.cfg \
vendor/moto/targa/proprietary/etc/omapcam/SEN2.cfg:/system/etc/omapcam/SEN2.cfg \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_cid1039_capabilities.bin:/system/etc/omapcam/module1.bak/cid1039_cid1039_capabilities.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_ae_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_ae_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_ae_mms2_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_ae_mms2_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_affw_dcc_tuning.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_affw_dcc_tuning.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_caf_dcc_tuning.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_caf_dcc_tuning.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_hllc_dcc_tuning.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_hllc_dcc_tuning.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_saf_dcc_tuning.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_saf_dcc_tuning.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_alg_adjust_rgb2rgb_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_alg_adjust_rgb2rgb_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_awb_alg_ti3_tuning.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_awb_alg_ti3_tuning.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ducati_eff_tun.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ducati_eff_tun.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ducati_gamma.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ducati_gamma.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ducati_lsc_2d.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ducati_lsc_2d.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ducati_nsf_ldc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ducati_nsf_ldc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_gbce_sw1_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_gbce_sw1_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_golden_module_calibration.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_golden_module_calibration.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_h3a_aewb_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_h3a_aewb_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_3d_lut_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_3d_lut_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_car_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_car_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_cfai_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_cfai_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_cgs_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_cgs_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_dpc_lut_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_dpc_lut_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_dpc_otf.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_dpc_otf.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_ee_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_ee_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_gbce_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_gbce_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_gic_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_gic_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_lsc_poly_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_lsc_poly_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_nf1_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_nf1_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_nf2_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_nf2_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rgb2rgb_1_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rgb2rgb_1_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rgb2rgb_2_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rgb2rgb_2_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rgb2yuv_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rgb2yuv_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rsz_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rsz_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_yuv444_to_yuv422_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_yuv444_to_yuv422_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_isif_clamp_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_isif_clamp_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_isif_csc_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_isif_csc_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_iss_glbce3_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_iss_glbce3_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_iss_lbce_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_iss_lbce_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_iss_scene_modes_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_iss_scene_modes_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_iss_vstab_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_iss_vstab_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ldc_cac_cfg_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ldc_cac_cfg_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ldc_cfg_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ldc_cfg_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_lsc_interp.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_lsc_interp.bin \
vendor/moto/targa/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_vnf_cfg_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_vnf_cfg_dcc.bin \
vendor/moto/targa/proprietary/etc/omapcam/module2/cid1040_ov7739_sensor_config_dcc.bin:/system/etc/omapcam/module2/cid1040_ov7739_sensor_config_dcc.bin \
vendor/moto/targa/proprietary/etc/ppp/peers/pppd-ril.options:/system/etc/ppp/peers/pppd-ril.options \
vendor/moto/targa/proprietary/etc/security/mancacerts.zip:/system/etc/security/mancacerts.zip \
vendor/moto/targa/proprietary/etc/security/oprcacerts.zip:/system/etc/security/oprcacerts.zip \
vendor/moto/targa/proprietary/etc/security/suplcerts.bks:/system/etc/security/suplcerts.bks \
vendor/moto/targa/proprietary/etc/spellchecker/en_US.aff:/system/etc/spellchecker/en_US.aff \
vendor/moto/targa/proprietary/etc/spellchecker/en_US.dic:/system/etc/spellchecker/en_US.dic \
vendor/moto/targa/proprietary/etc/spellchecker/es_ES.aff:/system/etc/spellchecker/es_ES.aff \
vendor/moto/targa/proprietary/etc/spellchecker/es_ES.dic:/system/etc/spellchecker/es_ES.dic \
vendor/moto/targa/proprietary/etc/updatecmds/google_generic_update.txt:/system/etc/updatecmds/google_generic_update.txt \
vendor/moto/targa/proprietary/etc/VideoEditorLite/mve.ini:/system/etc/VideoEditorLite/mve.ini \
vendor/moto/targa/proprietary/etc/vsensor.d/MeaningFulLocation.vsensor:/system/etc/vsensor.d/MeaningFulLocation.vsensor \
vendor/moto/targa/proprietary/etc/wifi/fw_wlan1281.bin:/system/etc/wifi/fw_wlan1281.bin \
vendor/moto/targa/proprietary/etc/wifi/fw_wlan1281_AP.bin:/system/etc/wifi/fw_wlan1281_AP.bin \
vendor/moto/targa/proprietary/etc/wifi/hostapd.conf.templet:/system/etc/wifi/hostapd.conf.templet \
vendor/moto/targa/proprietary/etc/motorola/12m/key_code_map.txt:system/etc/motorola/12m/key_code_map.txt \


# system/lib
PRODUCT_COPY_FILES += \
vendor/moto/targa/proprietary/lib/libadkutils.so:/system/lib/libadkutils.so \
vendor/moto/targa/proprietary/lib/libamcm.so:/system/lib/libamcm.so \
vendor/moto/targa/proprietary/lib/libb64.so:/system/lib/libb64.so \
vendor/moto/targa/proprietary/lib/libbabysit.so:/system/lib/libbabysit.so \
vendor/moto/targa/proprietary/lib/libbattd.so:/system/lib/libbattd.so \
vendor/moto/targa/proprietary/lib/libbcbmsg.so:/system/lib/libbcbmsg.so \
vendor/moto/targa/proprietary/lib/libcaps.so:/system/lib/libcaps.so \
vendor/moto/targa/proprietary/lib/libcapsjava.so:/system/lib/libcapsjava.so \
vendor/moto/targa/proprietary/lib/libdlnahttpjni.so:/system/lib/libdlnahttpjni.so \
vendor/moto/targa/proprietary/lib/libdlnajni.so:/system/lib/libdlnajni.so \
vendor/moto/targa/proprietary/lib/libdlnaprofileparser.so:/system/lib/libdlnaprofileparser.so \
vendor/moto/targa/proprietary/lib/libdlnasysjni.so:/system/lib/libdlnasysjni.so \
vendor/moto/targa/proprietary/lib/libdmengine.so:/system/lib/libdmengine.so \
vendor/moto/targa/proprietary/lib/libdmjavaplugin.so:/system/lib/libdmjavaplugin.so \
vendor/moto/targa/proprietary/lib/libexempi.so:/system/lib/libexempi.so \
vendor/moto/targa/proprietary/lib/libextdisp.so:/system/lib/libextdisp.so \
vendor/moto/targa/proprietary/lib/libgcomm_jni.so:/system/lib/libgcomm_jni.so \
vendor/moto/targa/proprietary/lib/libgdx.so:/system/lib/libgdx.so \
vendor/moto/targa/proprietary/lib/libhdcp.so:/system/lib/libhdcp.so \
vendor/moto/targa/proprietary/lib/libhdmi.so:/system/lib/libhdmi.so \
vendor/moto/targa/proprietary/lib/libhdr_interface.so:/system/lib/libhdr_interface.so \
vendor/moto/targa/proprietary/lib/libhostapd_client.so:/system/lib/libhostapd_client.so \
vendor/moto/targa/proprietary/lib/libimage_jni.so:/system/lib/libimage_jni.so \
vendor/moto/targa/proprietary/lib/libjanus.so:/system/lib/libjanus.so \
vendor/moto/targa/proprietary/lib/libjni_nwp.so:/system/lib/libjni_nwp.so \
vendor/moto/targa/proprietary/lib/libkpilogger.so:/system/lib/libkpilogger.so \
vendor/moto/targa/proprietary/lib/libmetainfo.so:/system/lib/libmetainfo.so \
vendor/moto/targa/proprietary/lib/libmirror.so:/system/lib/libmirror.so \
vendor/moto/targa/proprietary/lib/libmirrorjni.so:/system/lib/libmirrorjni.so \
vendor/moto/targa/proprietary/lib/libmot_atcmd.so:/system/lib/libmot_atcmd.so \
vendor/moto/targa/proprietary/lib/libmot_atcmd_mflex.so:/system/lib/libmot_atcmd_mflex.so \
vendor/moto/targa/proprietary/lib/libmot_bluetooth_jni.so:/system/lib/libmot_bluetooth_jni.so \
vendor/moto/targa/proprietary/lib/libmot_bthid_jni.so:/system/lib/libmot_bthid_jni.so \
vendor/moto/targa/proprietary/lib/libmot_btpan_jni.so:/system/lib/libmot_btpan_jni.so \
vendor/moto/targa/proprietary/lib/libmot_led.so:/system/lib/libmot_led.so \
vendor/moto/targa/proprietary/lib/libmotdb.so:/system/lib/libmotdb.so \
vendor/moto/targa/proprietary/lib/libmotdrm1.so:/system/lib/libmotdrm1.so \
vendor/moto/targa/proprietary/lib/libmotdrm1_jni.so:/system/lib/libmotdrm1_jni.so \
vendor/moto/targa/proprietary/lib/libmotodbgutils.so:/system/lib/libmotodbgutils.so \
vendor/moto/targa/proprietary/lib/libmtp_jni.so:/system/lib/libmtp_jni.so \
vendor/moto/targa/proprietary/lib/libmtpstack.so:/system/lib/libmtpstack.so \
vendor/moto/targa/proprietary/lib/libnative_renderer.so:/system/lib/libnative_renderer.so \
vendor/moto/targa/proprietary/lib/libnativedrm1.so:/system/lib/libnativedrm1.so \
vendor/moto/targa/proprietary/lib/libnbgm.so:/system/lib/libnbgm.so \
vendor/moto/targa/proprietary/lib/libmoto_netutil.so:/system/lib/libmoto_netutil.so \
vendor/moto/targa/proprietary/lib/libnmea.so:/system/lib/libnmea.so \
vendor/moto/targa/proprietary/lib/libOMX.ITTIAM.AAC.encode.so:/system/lib/libOMX.ITTIAM.AAC.encode.so \
vendor/moto/targa/proprietary/lib/libOMX.ITTIAM.WMA.decode.so:/system/lib/libOMX.ITTIAM.WMA.decode.so \
vendor/moto/targa/proprietary/lib/libpanorama.so:/system/lib/libpanorama.so \
vendor/moto/targa/proprietary/lib/libpanorama_jni.so:/system/lib/libpanorama_jni.so \
vendor/moto/targa/proprietary/lib/libPhotoEditor.so:/system/lib/libPhotoEditor.so \
vendor/moto/targa/proprietary/lib/libphotoflow.so:/system/lib/libphotoflow.so \
vendor/moto/targa/proprietary/lib/libpkip.so:/system/lib/libpkip.so \
vendor/moto/targa/proprietary/lib/libportaljni.so:/system/lib/libportaljni.so \
vendor/moto/targa/proprietary/lib/libpppd_plugin-ril.so:/system/lib/libpppd_plugin-ril.so \
vendor/moto/targa/proprietary/lib/libprojectM.so:/system/lib/libprojectM.so \
vendor/moto/targa/proprietary/lib/libprovlib.so:/system/lib/libprovlib.so \
vendor/moto/targa/proprietary/lib/libquicksec.so:/system/lib/libquicksec.so \
vendor/moto/targa/proprietary/lib/librds_util.so:/system/lib/librds_util.so \
vendor/moto/targa/proprietary/lib/libril_rds.so:/system/lib/libril_rds.so \
vendor/moto/targa/proprietary/lib/libscalado.so:/system/lib/libscalado.so \
vendor/moto/targa/proprietary/lib/libsmapi.so:/system/lib/libsmapi.so \
vendor/moto/targa/proprietary/lib/libspellingcheckengine.so:/system/lib/libspellingcheckengine.so \
vendor/moto/targa/proprietary/lib/libssmgr.so:/system/lib/libssmgr.so \
vendor/moto/targa/proprietary/lib/libtexture_mem.so:/system/lib/libtexture_mem.so \
vendor/moto/targa/proprietary/lib/libtf_crypto_sst.so:/system/lib/libtf_crypto_sst.so \
vendor/moto/targa/proprietary/lib/libtpa.so:/system/lib/libtpa.so \
vendor/moto/targa/proprietary/lib/libtpa_core.so:/system/lib/libtpa_core.so \
vendor/moto/targa/proprietary/lib/libui3d.so:/system/lib/libui3d.so \
vendor/moto/targa/proprietary/lib/libvideoeditorlite.so:/system/lib/libvideoeditorlite.so \
vendor/moto/targa/proprietary/lib/libvoicesearch.so:/system/lib/libvoicesearch.so \
vendor/moto/targa/proprietary/lib/libvorbisenc.so:/system/lib/libvorbisenc.so \
vendor/moto/targa/proprietary/lib/libvpnclient_jni.so:/system/lib/libvpnclient_jni.so \
vendor/moto/targa/proprietary/lib/libvsuite_mot_vs32_cmb103.so:/system/lib/libvsuite_mot_vs32_cmb103.so \
vendor/moto/targa/proprietary/lib/libwbxmlparser.so:/system/lib/libwbxmlparser.so \
vendor/moto/targa/proprietary/lib/libWifiAPHardware.so:/system/lib/libWifiAPHardware.so \
vendor/moto/targa/proprietary/lib/libXmp_jni.so:/system/lib/libXmp_jni.so \
vendor/moto/targa/proprietary/lib/libxmpcore.so:/system/lib/libxmpcore.so \

#vendor/moto/targa/proprietary/lib/libipsec.so:/system/lib/libipsec.so \
#vendor/moto/targa/proprietary/bin/rild:/system/bin/rild \
#vendor/moto/targa/proprietary/bin/libreference-ril.so:/system/lib/libreference-ril.so \
#vendor/moto/targa/proprietary/bin/libril.so:/system/lib/libril.so \
# RIL
PRODUCT_COPY_FILES += \
vendor/moto/targa/proprietary/lib/lib-mot-lte-ril.so:/system/lib/lib-mot-lte-ril.so \
vendor/moto/targa/proprietary/lib/libmotintfutil.so:/system/lib/libmotintfutil.so \
vendor/moto/targa/proprietary/lib/libmoto_mdmctrl.so:/system/lib/libmoto_mdmctrl.so \
vendor/moto/targa/proprietary/lib/libmoto_nwif_ril.so:/system/lib/libmoto_nwif_ril.so \
vendor/moto/targa/proprietary/lib/libmoto_qmi_ril.so:/system/lib/libmoto_qmi_ril.so \
vendor/moto/targa/proprietary/lib/libmoto_ril.so:/system/lib/libmoto_ril.so \
vendor/moto/targa/proprietary/lib/libreference-cdma-sms.so:/system/lib/libreference-cdma-sms.so \
vendor/moto/targa/proprietary/lib/moto-ril-multimode.so:/system/lib/moto-ril-multimode.so \

# system/lib/ducati
PRODUCT_COPY_FILES += \
vendor/moto/targa/proprietary/lib/ducati/Notify_MPUAPP_reroute_Test_Core1.xem3:/system/lib/ducati/Notify_MPUAPP_reroute_Test_Core1.xem3 \
vendor/moto/targa/proprietary/lib/ducati/Notify_MPUSYS_Test_Core0.xem3:/system/lib/ducati/Notify_MPUSYS_Test_Core0.xem3 \
vendor/moto/targa/proprietary/lib/ducati/Notify_MPUSYS_reroute_Test_Core0.xem3:/system/lib/ducati/Notify_MPUSYS_reroute_Test_Core0.xem3 \
vendor/moto/targa/proprietary/lib/ducati/base_image_app_m3.xem3:/system/lib/ducati/base_image_app_m3.xem3 \

# system/lib/hw
PRODUCT_COPY_FILES += \
vendor/moto/targa/proprietary/lib/hw/gps.targa.so:/system/lib/hw/gps.targa.so \
vendor/moto/targa/proprietary/lib/hw/lights.targa.so:/system/lib/hw/lights.targa.so \
vendor/moto/targa/proprietary/lib/hw/sensors.targa.so:/system/lib/hw/sensors.targa.so \

# system/usr
PRODUCT_COPY_FILES += \
vendor/moto/targa/proprietary/usr/share/alsa/init/00main:system/usr/share/alsa/init/00main \
vendor/moto/targa/proprietary/usr/share/alsa/init/default:system/usr/share/alsa/init/default \
vendor/moto/targa/proprietary/usr/share/alsa/init/hda:system/usr/share/alsa/init/hda \
vendor/moto/targa/proprietary/usr/share/alsa/init/info:system/usr/share/alsa/init/info \
vendor/moto/targa/proprietary/usr/share/alsa/init/test:system/usr/share/alsa/init/test \
vendor/moto/targa/proprietary/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
vendor/moto/targa/proprietary/usr/share/alsa/cards/aliases.conf:system/usr/share/alsa/cards/aliases.conf \
vendor/moto/targa/proprietary/usr/share/alsa/pcm/center_lfe.conf:system/usr/share/alsa/pcm/center_lfe.conf \
vendor/moto/targa/proprietary/usr/share/alsa/pcm/default.conf:system/usr/share/alsa/pcm/default.conf \
vendor/moto/targa/proprietary/usr/share/alsa/pcm/dmix.conf:system/usr/share/alsa/pcm/dmix.conf \
vendor/moto/targa/proprietary/usr/share/alsa/pcm/dpl.conf:system/usr/share/alsa/pcm/dpl.conf \
vendor/moto/targa/proprietary/usr/share/alsa/pcm/dsnoop.conf:system/usr/share/alsa/pcm/dsnoop.conf \
vendor/moto/targa/proprietary/usr/share/alsa/pcm/front.conf:system/usr/share/alsa/pcm/front.conf \
vendor/moto/targa/proprietary/usr/share/alsa/pcm/iec958.conf:system/usr/share/alsa/pcm/iec958.conf \
vendor/moto/targa/proprietary/usr/share/alsa/pcm/modem.conf:system/usr/share/alsa/pcm/modem.conf \
vendor/moto/targa/proprietary/usr/share/alsa/pcm/rear.conf:system/usr/share/alsa/pcm/rear.conf \
vendor/moto/targa/proprietary/usr/share/alsa/pcm/side.conf:system/usr/share/alsa/pcm/side.conf \
vendor/moto/targa/proprietary/usr/share/alsa/pcm/surround40.conf:system/usr/share/alsa/pcm/surround40.conf \
vendor/moto/targa/proprietary/usr/share/alsa/pcm/surround41.conf:system/usr/share/alsa/pcm/surround41.conf \
vendor/moto/targa/proprietary/usr/share/alsa/pcm/surround50.conf:system/usr/share/alsa/pcm/surround50.conf \
vendor/moto/targa/proprietary/usr/share/alsa/pcm/surround51.conf:system/usr/share/alsa/pcm/surround51.conf \
vendor/moto/targa/proprietary/usr/share/alsa/pcm/surround71.conf:system/usr/share/alsa/pcm/surround71.conf

# system/xbin
PRODUCT_COPY_FILES += \
vendor/moto/targa/proprietary/xbin/drm1_func_test:/system/xbin/drm1_func_test \
vendor/moto/targa/proprietary/xbin/ssmgrd:/system/xbin/ssmgrd \

# permissions
PRODUCT_COPY_FILES += \
vendor/moto/targa/proprietary/etc/permissions/platform.xml:/system/etc/permissions/platform.xml \
vendor/moto/targa/proprietary/etc/permissions/com.motorola.android.iextdispservice.xml:/system/etc/permissions/com.motorola.android.iextdispservice.xml \
vendor/moto/targa/proprietary/etc/permissions/com.motorola.android.imirrorservice.xml:/system/etc/permissions/com.motorola.android.imirrorservice.xml \
vendor/moto/targa/proprietary/etc/permissions/com.motorola.android.nativehdmiapis_v1.xml:/system/etc/permissoins/com.motorola.android.nativehdmiapis_v1.xml \

PRODUCT_PACKAGES += \
	ExtDispService \
	GlobalUnplug \
	MirrorService \
	PhoneConfig \
	XternalDisplay \
	com.motorola.android.iextdispservice \
	com.motorola.android.imirrorservice \
	com.motorola.android.nativehdmiapis_v1 \
